development:
  adapter: postgresql
  encoding: unicode
  database: vashavtoelektrik_development
  pool: 5
  host: localhost
  username: vashavtoelektrik
  password: qwaszx@1

test:
  adapter: postgresql
  encoding: unicode
  database: vashavtoelektrik_test
  pool: 5
  host: localhost
  username: vashavtoelektrik
  password: qwaszx@1

production:
  adapter: postgresql
  encoding: unicode
  database: vashavtoelektrik_production
  pool: 5
  username: vashavtoelektrik
  password: 1111
